[package]
name = "quic-echo-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
clap = "4.4.2"
futures = "0.3"
quinn = "0.6"
tokio = {version = "0.2", features = ["full"]}
