version: "3"

#コンテナ
services:
  #ftp
  ftp_server:
    image: stilliard/pure-ftpd
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    environment:
      - PUBLICHOST=0.0.0.0
      - FTP_USER_NAME=uname
      - FTP_USER_PASS=uP@ssw0rd
      - FTP_USER_HOME=/home/uname
    networks:
      my_network:
        ipv4_address: 172.25.1.3
    restart: always

  #DNS
  dns_server:
    build: .
    container_name: coredns
    restart: on-failure
    expose:
      - '53'
      - '53/udp'
    ports:
      - '20053:53'
      - '20053:53/udp'
    volumes:
      - './volumes/config:/etc/coredns'
    networks:
      my_network:
        ipv4_address: 172.25.1.4


networks:
  my_network:
    driver: bridge
    name: my_network
    ipam:
      driver: default
      config:
        - subnet: 172.25.1.0/24
